### ISSUE TITLE
Ticking screen issue?

### ISSUE THREAD

**Issue by GamerIn** [chylex/Resource-Pack-Organizer#14]
Every time I try to scroll down my server list this crash happens.
![why](https://user-images.githubusercontent.com/33606448/33231892-c0d7e0f6-d1ca-11e7-8ee6-57f83f642f3e.PNG)
Any help?

**Comment by chylex** [comment]
Need full crash report.

**Comment by GamerIn** [comment]
its not letting me see the full crash report

**Comment by chylex** [comment]
Try going to `.minecraft/crash-reports` or `.minecraft/logs` and find the file with the crash.

**Comment by GamerIn** [comment]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/25/17 3:01 PM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at io.netty.bootstrap.Bootstrap.checkAddress(Bootstrap.java:273)
	at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:150)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:132)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:113)
	at net.minecraft.client.network.OldServerPinger.func_147225_b(OldServerPinger.java:275)
	at net.minecraft.client.network.OldServerPinger.access$100(OldServerPinger.java:49)
	at net.minecraft.client.network.OldServerPinger$1.func_147231_a(OldServerPinger.java:173)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453)
	at net.minecraft.client.network.OldServerPinger.func_147223_a(OldServerPinger.java:295)
	at net.minecraft.client.gui.GuiMultiplayer.func_73876_c(GuiMultiplayer.java:108)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at io.netty.bootstrap.Bootstrap.checkAddress(Bootstrap.java:273)
	at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:150)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:132)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:113)
	at net.minecraft.client.network.OldServerPinger.func_147225_b(OldServerPinger.java:275)
	at net.minecraft.client.network.OldServerPinger.access$100(OldServerPinger.java:49)
	at net.minecraft.client.network.OldServerPinger$1.func_147231_a(OldServerPinger.java:173)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453)
	at net.minecraft.client.network.OldServerPinger.func_147223_a(OldServerPinger.java:295)
	at net.minecraft.client.gui.GuiMultiplayer.func_73876_c(GuiMultiplayer.java:108)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMultiplayer
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 772121760 bytes (736 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJAAAAAA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4549' Renderer: 'Intel(R) HD Graphics 530'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 20.19.15.4549, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ¦)fHalf
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Comment by chylex** [comment]
RPO isn't even installed..
